pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  only:
    - dev

